//LOCALHOST
###Get all contacts
GET http://localhost:3000/contacts

###Get contacts by ID
GET http://localhost:3000/contacts/6786b0d53aa79e85e5f9a551

###CREATE contacts
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Liezl",
    "lastName": "Lizardo",
    "email": "liezl1106@gmail.com",
    "favoriteColor": "green",
    "birthday": "11/06/1976"
}

###UPDATE contacts
PUT http://localhost:3000/contacts/6786b0d53aa79e85e5f9a552

{
    "firstName": "Larnel",
    "lastName": "Boron",
    "email": "larnel@gmail.com",
    "favoriteColor": "yellow",
    "birthday": "04/17/1972"
}

###DELETE contacts
DELETE http://localhost:3000/contacts/6786b0d53aa79e85e5f9a552
Content-Type: application/json

{
    "firstName": null,
    "lastName": null,
    "email": null,
    "favoriteColor": null,
    "birthday": null
}