//LOCALHOST
###Get all contacts
GET http://localhost:3000/contacts

###Get contacts by ID
GET http://localhost:3000/contacts/6786b0d53aa79e85e5f9a551

###CREATE contacts
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Larnel",
    "lastName": "Boron",
    "email": "larnel0418@gmail.com",
    "favoriteColor": "green",
    "birthday": "04/17/1972"
}

###PUT contacts
PUT http://localhost:3000/contacts/678cad91ab160cbc15c5a3bb
Content-Type: application/json

{
    "firstName": "Larnel",
    "lastName": "Boron",
    "email": "larnelb0418@gmail.com",
    "favoriteColor": "green",
    "birthday": "04/17/1972"
}

###DELETE contacts
DELETE http://localhost:3000/contacts/678ca8d7679a652d63b92123
Content-Type: application/json